# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transferchain.protobuf.service_pb2 as service__pb2


class FileOperationStub(object):
  """Missing associated documentation comment in .proto file."""

  def __init__(self, channel):
    """Constructor.

    Args:
        channel: A grpc.Channel.
    """
    self.TransferInit = channel.unary_unary(
      '/service.FileOperation/TransferInit',
      request_serializer=service__pb2.TransferInitRequest.SerializeToString,
      response_deserializer=service__pb2.TransferInitResponse.FromString,
    )
    self.TransferInitV2 = channel.unary_unary(
      '/service.FileOperation/TransferInitV2',
      request_serializer=service__pb2.TransferInitRequest.SerializeToString,
      response_deserializer=service__pb2.TransferInitResponse.FromString,
    )
    self.Transfer = channel.stream_unary(
      '/service.FileOperation/Transfer',
      request_serializer=service__pb2.TransferRequest.SerializeToString,
      response_deserializer=service__pb2.TransferResponse.FromString,
    )
    self.TransferV2 = channel.stream_unary(
      '/service.FileOperation/TransferV2',
      request_serializer=service__pb2.TransferRequest.SerializeToString,
      response_deserializer=service__pb2.TransferResponse.FromString,
    )
    self.TransferFinish = channel.unary_unary(
      '/service.FileOperation/TransferFinish',
      request_serializer=service__pb2.TransferFinishRequest.SerializeToString,
      response_deserializer=service__pb2.TransferFinishResponse.FromString,
    )
    self.TransferFinishV2 = channel.unary_unary(
      '/service.FileOperation/TransferFinishV2',
      request_serializer=service__pb2.TransferFinishRequest.SerializeToString,
      response_deserializer=service__pb2.TransferFinishResponse.FromString,
    )
    self.StorageInit = channel.unary_unary(
      '/service.FileOperation/StorageInit',
      request_serializer=service__pb2.StorageInitRequest.SerializeToString,
      response_deserializer=service__pb2.StorageInitResponse.FromString,
    )
    self.StorageInitV2 = channel.unary_unary(
      '/service.FileOperation/StorageInitV2',
      request_serializer=service__pb2.StorageInitRequest.SerializeToString,
      response_deserializer=service__pb2.StorageInitResponse.FromString,
    )
    self.StorageFinish = channel.unary_unary(
      '/service.FileOperation/StorageFinish',
      request_serializer=service__pb2.StorageFinishRequest.SerializeToString,
      response_deserializer=service__pb2.StorageFinishResponse.FromString,
    )
    self.StorageFinishV2 = channel.unary_unary(
      '/service.FileOperation/StorageFinishV2',
      request_serializer=service__pb2.StorageFinishRequest.SerializeToString,
      response_deserializer=service__pb2.StorageFinishResponse.FromString,
    )
    self.UploadInit = channel.unary_unary(
      '/service.FileOperation/UploadInit',
      request_serializer=service__pb2.UploadInitRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.UploadInitV2 = channel.unary_unary(
      '/service.FileOperation/UploadInitV2',
      request_serializer=service__pb2.UploadInitRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.UploadBasic = channel.stream_unary(
      '/service.FileOperation/UploadBasic',
      request_serializer=service__pb2.UploadRequest.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.UploadBasicV2 = channel.stream_unary(
      '/service.FileOperation/UploadBasicV2',
      request_serializer=service__pb2.UploadRequest.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.UploadBasicV3 = channel.stream_unary(
      '/service.FileOperation/UploadBasicV3',
      request_serializer=service__pb2.UploadV3Request.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.UploadBasicV4 = channel.stream_unary(
      '/service.FileOperation/UploadBasicV4',
      request_serializer=service__pb2.UploadV3Request.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.TransferToUpload = channel.unary_unary(
      '/service.FileOperation/TransferToUpload',
      request_serializer=service__pb2.TransferToUploadRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.TransferToStorage = channel.unary_unary(
      '/service.FileOperation/TransferToStorage',
      request_serializer=service__pb2.TransferToStorageRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.Download = channel.unary_stream(
      '/service.FileOperation/Download',
      request_serializer=service__pb2.DownloadRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.DownloadV2 = channel.unary_stream(
      '/service.FileOperation/DownloadV2',
      request_serializer=service__pb2.DownloadV2Request.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.DownloadV3 = channel.unary_stream(
      '/service.FileOperation/DownloadV3',
      request_serializer=service__pb2.DownloadRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.DownloadV4 = channel.unary_unary(
      '/service.FileOperation/DownloadV4',
      request_serializer=service__pb2.DownloadV4Request.SerializeToString,
      response_deserializer=service__pb2.DownloadV4Response.FromString,
    )
    self.DownloadInfo = channel.unary_unary(
      '/service.FileOperation/DownloadInfo',
      request_serializer=service__pb2.DownloadInfoRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadInfoResponse.FromString,
    )
    self.Delete = channel.unary_unary(
      '/service.FileOperation/Delete',
      request_serializer=service__pb2.DeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.DeleteV2 = channel.unary_unary(
      '/service.FileOperation/DeleteV2',
      request_serializer=service__pb2.DeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.DeleteV3 = channel.unary_unary(
      '/service.FileOperation/DeleteV3',
      request_serializer=service__pb2.DeleteV3Request.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.Message = channel.unary_unary(
      '/service.FileOperation/Message',
      request_serializer=service__pb2.MessageRequest.SerializeToString,
      response_deserializer=service__pb2.MessageResponse.FromString,
    )
    self.DropAccount = channel.unary_unary(
      '/service.FileOperation/DropAccount',
      request_serializer=service__pb2.DropAccountRequest.SerializeToString,
      response_deserializer=service__pb2.DropAccountResponse.FromString,
    )
    self.Heartbeat = channel.unary_unary(
      '/service.FileOperation/Heartbeat',
      request_serializer=service__pb2.Empty.SerializeToString,
      response_deserializer=service__pb2.Empty.FromString,
    )
    self.RequestsUpdate = channel.unary_unary(
      '/service.FileOperation/RequestsUpdate',
      request_serializer=service__pb2.RequestsUpdateRequest.SerializeToString,
      response_deserializer=service__pb2.RequestsResponse.FromString,
    )
    self.RequestsCreate = channel.unary_unary(
      '/service.FileOperation/RequestsCreate',
      request_serializer=service__pb2.RequestsCreateRequest.SerializeToString,
      response_deserializer=service__pb2.RequestsResponse.FromString,
    )
    self.DataRoomCreate = channel.unary_unary(
      '/service.FileOperation/DataRoomCreate',
      request_serializer=service__pb2.DataRoomCreateRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomCreateResponse.FromString,
    )
    self.DataRoomDelete = channel.unary_unary(
      '/service.FileOperation/DataRoomDelete',
      request_serializer=service__pb2.DataRoomDeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomDeleteResponse.FromString,
    )
    self.DataRoomPolicyCreate = channel.unary_unary(
      '/service.FileOperation/DataRoomPolicyCreate',
      request_serializer=service__pb2.DataRoomPolicyCreateRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomPolicyCreateResponse.FromString,
    )
    self.DataRoomPolicyDelete = channel.unary_unary(
      '/service.FileOperation/DataRoomPolicyDelete',
      request_serializer=service__pb2.DataRoomPolicyDeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomPolicyDeleteResponse.FromString,
    )
    self.DataRoomLeave = channel.unary_unary(
      '/service.FileOperation/DataRoomLeave',
      request_serializer=service__pb2.DataRoomLeaveRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomLeaveResponse.FromString,
    )
    self.DataPolicyCreate = channel.unary_unary(
      '/service.FileOperation/DataPolicyCreate',
      request_serializer=service__pb2.DataPolicyCreateRequest.SerializeToString,
      response_deserializer=service__pb2.DataPolicyCreateResponse.FromString,
    )
    self.DataPolicyDelete = channel.unary_unary(
      '/service.FileOperation/DataPolicyDelete',
      request_serializer=service__pb2.DataPolicyDeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DataPolicyDeleteResponse.FromString,
    )
    self.DataLogs = channel.unary_unary(
      '/service.FileOperation/DataLogs',
      request_serializer=service__pb2.DataLogListRequest.SerializeToString,
      response_deserializer=service__pb2.DataLogListResponse.FromString,
    )


class FileOperationServicer(object):
  """Missing associated documentation comment in .proto file."""

  def TransferInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferInitV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transfer(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferV2(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferFinish(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferFinishV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageInitV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageFinish(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageFinishV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadInitV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasic(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasicV2(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasicV3(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasicV4(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferToUpload(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferToStorage(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadV3(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadV4(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadInfo(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteV3(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Message(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DropAccount(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestsUpdate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestsCreate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomCreate(self, request, context):
    """DataRoom and Data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomDelete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomPolicyCreate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomPolicyDelete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomLeave(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataPolicyCreate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataPolicyDelete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataLogs(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileOperationServicer_to_server(servicer, server):
  rpc_method_handlers = {
    'TransferInit': grpc.unary_unary_rpc_method_handler(
      servicer.TransferInit,
      request_deserializer=service__pb2.TransferInitRequest.FromString,
      response_serializer=service__pb2.TransferInitResponse.SerializeToString,
    ),
    'TransferInitV2': grpc.unary_unary_rpc_method_handler(
      servicer.TransferInitV2,
      request_deserializer=service__pb2.TransferInitRequest.FromString,
      response_serializer=service__pb2.TransferInitResponse.SerializeToString,
    ),
    'Transfer': grpc.stream_unary_rpc_method_handler(
      servicer.Transfer,
      request_deserializer=service__pb2.TransferRequest.FromString,
      response_serializer=service__pb2.TransferResponse.SerializeToString,
    ),
    'TransferV2': grpc.stream_unary_rpc_method_handler(
      servicer.TransferV2,
      request_deserializer=service__pb2.TransferRequest.FromString,
      response_serializer=service__pb2.TransferResponse.SerializeToString,
    ),
    'TransferFinish': grpc.unary_unary_rpc_method_handler(
      servicer.TransferFinish,
      request_deserializer=service__pb2.TransferFinishRequest.FromString,
      response_serializer=service__pb2.TransferFinishResponse.SerializeToString,
    ),
    'TransferFinishV2': grpc.unary_unary_rpc_method_handler(
      servicer.TransferFinishV2,
      request_deserializer=service__pb2.TransferFinishRequest.FromString,
      response_serializer=service__pb2.TransferFinishResponse.SerializeToString,
    ),
    'StorageInit': grpc.unary_unary_rpc_method_handler(
      servicer.StorageInit,
      request_deserializer=service__pb2.StorageInitRequest.FromString,
      response_serializer=service__pb2.StorageInitResponse.SerializeToString,
    ),
    'StorageInitV2': grpc.unary_unary_rpc_method_handler(
      servicer.StorageInitV2,
      request_deserializer=service__pb2.StorageInitRequest.FromString,
      response_serializer=service__pb2.StorageInitResponse.SerializeToString,
    ),
    'StorageFinish': grpc.unary_unary_rpc_method_handler(
      servicer.StorageFinish,
      request_deserializer=service__pb2.StorageFinishRequest.FromString,
      response_serializer=service__pb2.StorageFinishResponse.SerializeToString,
    ),
    'StorageFinishV2': grpc.unary_unary_rpc_method_handler(
      servicer.StorageFinishV2,
      request_deserializer=service__pb2.StorageFinishRequest.FromString,
      response_serializer=service__pb2.StorageFinishResponse.SerializeToString,
    ),
    'UploadInit': grpc.unary_unary_rpc_method_handler(
      servicer.UploadInit,
      request_deserializer=service__pb2.UploadInitRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'UploadInitV2': grpc.unary_unary_rpc_method_handler(
      servicer.UploadInitV2,
      request_deserializer=service__pb2.UploadInitRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'UploadBasic': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasic,
      request_deserializer=service__pb2.UploadRequest.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'UploadBasicV2': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasicV2,
      request_deserializer=service__pb2.UploadRequest.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'UploadBasicV3': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasicV3,
      request_deserializer=service__pb2.UploadV3Request.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'UploadBasicV4': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasicV4,
      request_deserializer=service__pb2.UploadV3Request.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'TransferToUpload': grpc.unary_unary_rpc_method_handler(
      servicer.TransferToUpload,
      request_deserializer=service__pb2.TransferToUploadRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'TransferToStorage': grpc.unary_unary_rpc_method_handler(
      servicer.TransferToStorage,
      request_deserializer=service__pb2.TransferToStorageRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'Download': grpc.unary_stream_rpc_method_handler(
      servicer.Download,
      request_deserializer=service__pb2.DownloadRequest.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'DownloadV2': grpc.unary_stream_rpc_method_handler(
      servicer.DownloadV2,
      request_deserializer=service__pb2.DownloadV2Request.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'DownloadV3': grpc.unary_stream_rpc_method_handler(
      servicer.DownloadV3,
      request_deserializer=service__pb2.DownloadRequest.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'DownloadV4': grpc.unary_unary_rpc_method_handler(
      servicer.DownloadV4,
      request_deserializer=service__pb2.DownloadV4Request.FromString,
      response_serializer=service__pb2.DownloadV4Response.SerializeToString,
    ),
    'DownloadInfo': grpc.unary_unary_rpc_method_handler(
      servicer.DownloadInfo,
      request_deserializer=service__pb2.DownloadInfoRequest.FromString,
      response_serializer=service__pb2.DownloadInfoResponse.SerializeToString,
    ),
    'Delete': grpc.unary_unary_rpc_method_handler(
      servicer.Delete,
      request_deserializer=service__pb2.DeleteRequest.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'DeleteV2': grpc.unary_unary_rpc_method_handler(
      servicer.DeleteV2,
      request_deserializer=service__pb2.DeleteRequest.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'DeleteV3': grpc.unary_unary_rpc_method_handler(
      servicer.DeleteV3,
      request_deserializer=service__pb2.DeleteV3Request.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'Message': grpc.unary_unary_rpc_method_handler(
      servicer.Message,
      request_deserializer=service__pb2.MessageRequest.FromString,
      response_serializer=service__pb2.MessageResponse.SerializeToString,
    ),
    'DropAccount': grpc.unary_unary_rpc_method_handler(
      servicer.DropAccount,
      request_deserializer=service__pb2.DropAccountRequest.FromString,
      response_serializer=service__pb2.DropAccountResponse.SerializeToString,
    ),
    'Heartbeat': grpc.unary_unary_rpc_method_handler(
      servicer.Heartbeat,
      request_deserializer=service__pb2.Empty.FromString,
      response_serializer=service__pb2.Empty.SerializeToString,
    ),
    'RequestsUpdate': grpc.unary_unary_rpc_method_handler(
      servicer.RequestsUpdate,
      request_deserializer=service__pb2.RequestsUpdateRequest.FromString,
      response_serializer=service__pb2.RequestsResponse.SerializeToString,
    ),
    'RequestsCreate': grpc.unary_unary_rpc_method_handler(
      servicer.RequestsCreate,
      request_deserializer=service__pb2.RequestsCreateRequest.FromString,
      response_serializer=service__pb2.RequestsResponse.SerializeToString,
    ),
    'DataRoomCreate': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomCreate,
      request_deserializer=service__pb2.DataRoomCreateRequest.FromString,
      response_serializer=service__pb2.DataRoomCreateResponse.SerializeToString,
    ),
    'DataRoomDelete': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomDelete,
      request_deserializer=service__pb2.DataRoomDeleteRequest.FromString,
      response_serializer=service__pb2.DataRoomDeleteResponse.SerializeToString,
    ),
    'DataRoomPolicyCreate': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomPolicyCreate,
      request_deserializer=service__pb2.DataRoomPolicyCreateRequest.FromString,
      response_serializer=service__pb2.DataRoomPolicyCreateResponse.SerializeToString,
    ),
    'DataRoomPolicyDelete': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomPolicyDelete,
      request_deserializer=service__pb2.DataRoomPolicyDeleteRequest.FromString,
      response_serializer=service__pb2.DataRoomPolicyDeleteResponse.SerializeToString,
    ),
    'DataRoomLeave': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomLeave,
      request_deserializer=service__pb2.DataRoomLeaveRequest.FromString,
      response_serializer=service__pb2.DataRoomLeaveResponse.SerializeToString,
    ),
    'DataPolicyCreate': grpc.unary_unary_rpc_method_handler(
      servicer.DataPolicyCreate,
      request_deserializer=service__pb2.DataPolicyCreateRequest.FromString,
      response_serializer=service__pb2.DataPolicyCreateResponse.SerializeToString,
    ),
    'DataPolicyDelete': grpc.unary_unary_rpc_method_handler(
      servicer.DataPolicyDelete,
      request_deserializer=service__pb2.DataPolicyDeleteRequest.FromString,
      response_serializer=service__pb2.DataPolicyDeleteResponse.SerializeToString,
    ),
    'DataLogs': grpc.unary_unary_rpc_method_handler(
      servicer.DataLogs,
      request_deserializer=service__pb2.DataLogListRequest.FromString,
      response_serializer=service__pb2.DataLogListResponse.SerializeToString,
    ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
    'service.FileOperation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class FileOperation(object):
  """Missing associated documentation comment in .proto file."""

  @staticmethod
  def TransferInit(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/TransferInit',
                                         service__pb2.TransferInitRequest.SerializeToString,
                                         service__pb2.TransferInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferInitV2(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/TransferInitV2',
                                         service__pb2.TransferInitRequest.SerializeToString,
                                         service__pb2.TransferInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Transfer(request_iterator,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.FileOperation/Transfer',
                                          service__pb2.TransferRequest.SerializeToString,
                                          service__pb2.TransferResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferV2(request_iterator,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.FileOperation/TransferV2',
                                          service__pb2.TransferRequest.SerializeToString,
                                          service__pb2.TransferResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferFinish(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/TransferFinish',
                                         service__pb2.TransferFinishRequest.SerializeToString,
                                         service__pb2.TransferFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferFinishV2(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/TransferFinishV2',
                                         service__pb2.TransferFinishRequest.SerializeToString,
                                         service__pb2.TransferFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageInit(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/StorageInit',
                                         service__pb2.StorageInitRequest.SerializeToString,
                                         service__pb2.StorageInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageInitV2(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/StorageInitV2',
                                         service__pb2.StorageInitRequest.SerializeToString,
                                         service__pb2.StorageInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageFinish(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/StorageFinish',
                                         service__pb2.StorageFinishRequest.SerializeToString,
                                         service__pb2.StorageFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageFinishV2(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/StorageFinishV2',
                                         service__pb2.StorageFinishRequest.SerializeToString,
                                         service__pb2.StorageFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadInit(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/UploadInit',
                                         service__pb2.UploadInitRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadInitV2(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/UploadInitV2',
                                         service__pb2.UploadInitRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasic(request_iterator,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.FileOperation/UploadBasic',
                                          service__pb2.UploadRequest.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasicV2(request_iterator,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.FileOperation/UploadBasicV2',
                                          service__pb2.UploadRequest.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasicV3(request_iterator,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.FileOperation/UploadBasicV3',
                                          service__pb2.UploadV3Request.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasicV4(request_iterator,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.FileOperation/UploadBasicV4',
                                          service__pb2.UploadV3Request.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferToUpload(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/TransferToUpload',
                                         service__pb2.TransferToUploadRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferToStorage(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/TransferToStorage',
                                         service__pb2.TransferToStorageRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Download(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.FileOperation/Download',
                                          service__pb2.DownloadRequest.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadV2(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.FileOperation/DownloadV2',
                                          service__pb2.DownloadV2Request.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadV3(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.FileOperation/DownloadV3',
                                          service__pb2.DownloadRequest.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadV4(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DownloadV4',
                                         service__pb2.DownloadV4Request.SerializeToString,
                                         service__pb2.DownloadV4Response.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadInfo(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DownloadInfo',
                                         service__pb2.DownloadInfoRequest.SerializeToString,
                                         service__pb2.DownloadInfoResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Delete(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/Delete',
                                         service__pb2.DeleteRequest.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DeleteV2(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DeleteV2',
                                         service__pb2.DeleteRequest.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DeleteV3(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DeleteV3',
                                         service__pb2.DeleteV3Request.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Message(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/Message',
                                         service__pb2.MessageRequest.SerializeToString,
                                         service__pb2.MessageResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DropAccount(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DropAccount',
                                         service__pb2.DropAccountRequest.SerializeToString,
                                         service__pb2.DropAccountResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Heartbeat(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/Heartbeat',
                                         service__pb2.Empty.SerializeToString,
                                         service__pb2.Empty.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def RequestsUpdate(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/RequestsUpdate',
                                         service__pb2.RequestsUpdateRequest.SerializeToString,
                                         service__pb2.RequestsResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def RequestsCreate(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/RequestsCreate',
                                         service__pb2.RequestsCreateRequest.SerializeToString,
                                         service__pb2.RequestsResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomCreate(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataRoomCreate',
                                         service__pb2.DataRoomCreateRequest.SerializeToString,
                                         service__pb2.DataRoomCreateResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomDelete(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataRoomDelete',
                                         service__pb2.DataRoomDeleteRequest.SerializeToString,
                                         service__pb2.DataRoomDeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomPolicyCreate(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataRoomPolicyCreate',
                                         service__pb2.DataRoomPolicyCreateRequest.SerializeToString,
                                         service__pb2.DataRoomPolicyCreateResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomPolicyDelete(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataRoomPolicyDelete',
                                         service__pb2.DataRoomPolicyDeleteRequest.SerializeToString,
                                         service__pb2.DataRoomPolicyDeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomLeave(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataRoomLeave',
                                         service__pb2.DataRoomLeaveRequest.SerializeToString,
                                         service__pb2.DataRoomLeaveResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataPolicyCreate(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataPolicyCreate',
                                         service__pb2.DataPolicyCreateRequest.SerializeToString,
                                         service__pb2.DataPolicyCreateResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataPolicyDelete(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataPolicyDelete',
                                         service__pb2.DataPolicyDeleteRequest.SerializeToString,
                                         service__pb2.DataPolicyDeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataLogs(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.FileOperation/DataLogs',
                                         service__pb2.DataLogListRequest.SerializeToString,
                                         service__pb2.DataLogListResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
