# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transferchain.protobuf.service_pb2 as service__pb2


class tcRpcStub(object):
  """Missing associated documentation comment in .proto file."""

  def __init__(self, channel):
    """Constructor.

    Args:
        channel: A grpc.Channel.
    """
    self.TransferInit = channel.unary_unary(
      '/service.tcRpc/TransferInit',
      request_serializer=service__pb2.TransferInitRequest.SerializeToString,
      response_deserializer=service__pb2.TransferInitResponse.FromString,
    )
    self.AuthTransferInit = channel.unary_unary(
      '/service.tcRpc/AuthTransferInit',
      request_serializer=service__pb2.TransferInitRequest.SerializeToString,
      response_deserializer=service__pb2.TransferInitResponse.FromString,
    )
    self.TransferInitV2 = channel.unary_unary(
      '/service.tcRpc/TransferInitV2',
      request_serializer=service__pb2.TransferInitRequest.SerializeToString,
      response_deserializer=service__pb2.TransferInitResponse.FromString,
    )
    self.Transfer = channel.stream_unary(
      '/service.tcRpc/Transfer',
      request_serializer=service__pb2.TransferRequest.SerializeToString,
      response_deserializer=service__pb2.TransferResponse.FromString,
    )
    self.AuthTransfer = channel.stream_unary(
      '/service.tcRpc/AuthTransfer',
      request_serializer=service__pb2.TransferRequest.SerializeToString,
      response_deserializer=service__pb2.TransferResponse.FromString,
    )
    self.TransferV2 = channel.stream_unary(
      '/service.tcRpc/TransferV2',
      request_serializer=service__pb2.TransferRequest.SerializeToString,
      response_deserializer=service__pb2.TransferResponse.FromString,
    )
    self.TransferFinish = channel.unary_unary(
      '/service.tcRpc/TransferFinish',
      request_serializer=service__pb2.TransferFinishRequest.SerializeToString,
      response_deserializer=service__pb2.TransferFinishResponse.FromString,
    )
    self.AuthTransferFinish = channel.unary_unary(
      '/service.tcRpc/AuthTransferFinish',
      request_serializer=service__pb2.TransferFinishRequest.SerializeToString,
      response_deserializer=service__pb2.TransferFinishResponse.FromString,
    )
    self.TransferFinishV2 = channel.unary_unary(
      '/service.tcRpc/TransferFinishV2',
      request_serializer=service__pb2.TransferFinishRequest.SerializeToString,
      response_deserializer=service__pb2.TransferFinishResponse.FromString,
    )
    self.StorageInit = channel.unary_unary(
      '/service.tcRpc/StorageInit',
      request_serializer=service__pb2.StorageInitRequest.SerializeToString,
      response_deserializer=service__pb2.StorageInitResponse.FromString,
    )
    self.AuthStorageInit = channel.unary_unary(
      '/service.tcRpc/AuthStorageInit',
      request_serializer=service__pb2.StorageInitRequest.SerializeToString,
      response_deserializer=service__pb2.StorageInitResponse.FromString,
    )
    self.StorageInitV2 = channel.unary_unary(
      '/service.tcRpc/StorageInitV2',
      request_serializer=service__pb2.StorageInitRequest.SerializeToString,
      response_deserializer=service__pb2.StorageInitResponse.FromString,
    )
    self.StorageFinish = channel.unary_unary(
      '/service.tcRpc/StorageFinish',
      request_serializer=service__pb2.StorageFinishRequest.SerializeToString,
      response_deserializer=service__pb2.StorageFinishResponse.FromString,
    )
    self.AuthStorageFinish = channel.unary_unary(
      '/service.tcRpc/AuthStorageFinish',
      request_serializer=service__pb2.StorageFinishRequest.SerializeToString,
      response_deserializer=service__pb2.StorageFinishResponse.FromString,
    )
    self.StorageFinishV2 = channel.unary_unary(
      '/service.tcRpc/StorageFinishV2',
      request_serializer=service__pb2.StorageFinishRequest.SerializeToString,
      response_deserializer=service__pb2.StorageFinishResponse.FromString,
    )
    self.UploadInit = channel.unary_unary(
      '/service.tcRpc/UploadInit',
      request_serializer=service__pb2.UploadInitRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.AuthUploadInit = channel.unary_unary(
      '/service.tcRpc/AuthUploadInit',
      request_serializer=service__pb2.UploadInitRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.UploadInitV2 = channel.unary_unary(
      '/service.tcRpc/UploadInitV2',
      request_serializer=service__pb2.UploadInitRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.UploadBasic = channel.stream_unary(
      '/service.tcRpc/UploadBasic',
      request_serializer=service__pb2.UploadRequest.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.UploadBasicV2 = channel.stream_unary(
      '/service.tcRpc/UploadBasicV2',
      request_serializer=service__pb2.UploadRequest.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.UploadBasicV3 = channel.stream_unary(
      '/service.tcRpc/UploadBasicV3',
      request_serializer=service__pb2.UploadV3Request.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.UploadBasicV4 = channel.stream_unary(
      '/service.tcRpc/UploadBasicV4',
      request_serializer=service__pb2.UploadV3Request.SerializeToString,
      response_deserializer=service__pb2.UploadResponse.FromString,
    )
    self.TransferToUpload = channel.unary_unary(
      '/service.tcRpc/TransferToUpload',
      request_serializer=service__pb2.TransferToUploadRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.TransferToStorage = channel.unary_unary(
      '/service.tcRpc/TransferToStorage',
      request_serializer=service__pb2.TransferToStorageRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.AuthTransferToUpload = channel.unary_unary(
      '/service.tcRpc/AuthTransferToUpload',
      request_serializer=service__pb2.TransferToUploadRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.AuthTransferToStorage = channel.unary_unary(
      '/service.tcRpc/AuthTransferToStorage',
      request_serializer=service__pb2.TransferToStorageRequest.SerializeToString,
      response_deserializer=service__pb2.UploadInitResponse.FromString,
    )
    self.Download = channel.unary_stream(
      '/service.tcRpc/Download',
      request_serializer=service__pb2.DownloadRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.DownloadV2 = channel.unary_stream(
      '/service.tcRpc/DownloadV2',
      request_serializer=service__pb2.DownloadV2Request.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.AuthDownload = channel.unary_stream(
      '/service.tcRpc/AuthDownload',
      request_serializer=service__pb2.DownloadRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.AuthDownloadV2 = channel.unary_stream(
      '/service.tcRpc/AuthDownloadV2',
      request_serializer=service__pb2.DownloadV2Request.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.DownloadV3 = channel.unary_stream(
      '/service.tcRpc/DownloadV3',
      request_serializer=service__pb2.DownloadRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadResponse.FromString,
    )
    self.DownloadV4 = channel.unary_unary(
      '/service.tcRpc/DownloadV4',
      request_serializer=service__pb2.DownloadV4Request.SerializeToString,
      response_deserializer=service__pb2.DownloadV4Response.FromString,
    )
    self.AuthDownloadV4 = channel.unary_unary(
      '/service.tcRpc/AuthDownloadV4',
      request_serializer=service__pb2.DownloadV4Request.SerializeToString,
      response_deserializer=service__pb2.DownloadV4Response.FromString,
    )
    self.DownloadInfo = channel.unary_unary(
      '/service.tcRpc/DownloadInfo',
      request_serializer=service__pb2.DownloadInfoRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadInfoResponse.FromString,
    )
    self.AuthDownloadInfo = channel.unary_unary(
      '/service.tcRpc/AuthDownloadInfo',
      request_serializer=service__pb2.DownloadInfoRequest.SerializeToString,
      response_deserializer=service__pb2.DownloadInfoResponse.FromString,
    )
    self.Delete = channel.unary_unary(
      '/service.tcRpc/Delete',
      request_serializer=service__pb2.DeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.AuthDelete = channel.unary_unary(
      '/service.tcRpc/AuthDelete',
      request_serializer=service__pb2.DeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.DeleteV2 = channel.unary_unary(
      '/service.tcRpc/DeleteV2',
      request_serializer=service__pb2.DeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.DeleteV3 = channel.unary_unary(
      '/service.tcRpc/DeleteV3',
      request_serializer=service__pb2.DeleteV3Request.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.AuthDeleteV3 = channel.unary_unary(
      '/service.tcRpc/AuthDeleteV3',
      request_serializer=service__pb2.DeleteV3Request.SerializeToString,
      response_deserializer=service__pb2.DeleteResponse.FromString,
    )
    self.Message = channel.unary_unary(
      '/service.tcRpc/Message',
      request_serializer=service__pb2.MessageRequest.SerializeToString,
      response_deserializer=service__pb2.MessageResponse.FromString,
    )
    self.AuthMessage = channel.unary_unary(
      '/service.tcRpc/AuthMessage',
      request_serializer=service__pb2.MessageRequest.SerializeToString,
      response_deserializer=service__pb2.MessageResponse.FromString,
    )
    self.DropAccount = channel.unary_unary(
      '/service.tcRpc/DropAccount',
      request_serializer=service__pb2.DropAccountRequest.SerializeToString,
      response_deserializer=service__pb2.DropAccountResponse.FromString,
    )
    self.AuthDropAccount = channel.unary_unary(
      '/service.tcRpc/AuthDropAccount',
      request_serializer=service__pb2.DropAccountRequest.SerializeToString,
      response_deserializer=service__pb2.DropAccountResponse.FromString,
    )
    self.Heartbeat = channel.unary_unary(
      '/service.tcRpc/Heartbeat',
      request_serializer=service__pb2.Empty.SerializeToString,
      response_deserializer=service__pb2.Empty.FromString,
    )
    self.RequestsUpdate = channel.unary_unary(
      '/service.tcRpc/RequestsUpdate',
      request_serializer=service__pb2.RequestsUpdateRequest.SerializeToString,
      response_deserializer=service__pb2.RequestsResponse.FromString,
    )
    self.RequestsCreate = channel.unary_unary(
      '/service.tcRpc/RequestsCreate',
      request_serializer=service__pb2.RequestsCreateRequest.SerializeToString,
      response_deserializer=service__pb2.RequestsResponse.FromString,
    )
    self.AuthRequestsUpdate = channel.unary_unary(
      '/service.tcRpc/AuthRequestsUpdate',
      request_serializer=service__pb2.RequestsUpdateRequest.SerializeToString,
      response_deserializer=service__pb2.RequestsResponse.FromString,
    )
    self.AuthRequestsCreate = channel.unary_unary(
      '/service.tcRpc/AuthRequestsCreate',
      request_serializer=service__pb2.RequestsCreateRequest.SerializeToString,
      response_deserializer=service__pb2.RequestsResponse.FromString,
    )
    self.DataRoomCreate = channel.unary_unary(
      '/service.tcRpc/DataRoomCreate',
      request_serializer=service__pb2.DataRoomCreateRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomCreateResponse.FromString,
    )
    self.DataRoomDelete = channel.unary_unary(
      '/service.tcRpc/DataRoomDelete',
      request_serializer=service__pb2.DataRoomDeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomDeleteResponse.FromString,
    )
    self.DataRoomPolicyCreate = channel.unary_unary(
      '/service.tcRpc/DataRoomPolicyCreate',
      request_serializer=service__pb2.DataRoomPolicyCreateRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomPolicyCreateResponse.FromString,
    )
    self.DataRoomPolicyDelete = channel.unary_unary(
      '/service.tcRpc/DataRoomPolicyDelete',
      request_serializer=service__pb2.DataRoomPolicyDeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DataRoomPolicyDeleteResponse.FromString,
    )
    self.DataPolicyCreate = channel.unary_unary(
      '/service.tcRpc/DataPolicyCreate',
      request_serializer=service__pb2.DataPolicyCreateRequest.SerializeToString,
      response_deserializer=service__pb2.DataPolicyCreateResponse.FromString,
    )
    self.DataPolicyDelete = channel.unary_unary(
      '/service.tcRpc/DataPolicyDelete',
      request_serializer=service__pb2.DataPolicyDeleteRequest.SerializeToString,
      response_deserializer=service__pb2.DataPolicyDeleteResponse.FromString,
    )
    self.DataLogs = channel.unary_unary(
      '/service.tcRpc/DataLogs',
      request_serializer=service__pb2.DataLogListRequest.SerializeToString,
      response_deserializer=service__pb2.DataLogListResponse.FromString,
    )


class tcRpcServicer(object):
  """Missing associated documentation comment in .proto file."""

  def TransferInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthTransferInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferInitV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transfer(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthTransfer(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferV2(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferFinish(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthTransferFinish(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferFinishV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthStorageInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageInitV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageFinish(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthStorageFinish(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StorageFinishV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthUploadInit(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadInitV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasic(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasicV2(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasicV3(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBasicV4(self, request_iterator, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferToUpload(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferToStorage(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthTransferToUpload(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthTransferToStorage(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDownload(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDownloadV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadV3(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadV4(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDownloadV4(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadInfo(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDownloadInfo(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDelete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteV2(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteV3(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDeleteV3(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Message(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthMessage(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DropAccount(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthDropAccount(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Heartbeat(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestsUpdate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestsCreate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthRequestsUpdate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthRequestsCreate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomCreate(self, request, context):
    """DataRoom and Data
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomDelete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomPolicyCreate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataRoomPolicyDelete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataPolicyCreate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataPolicyDelete(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DataLogs(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_tcRpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
    'TransferInit': grpc.unary_unary_rpc_method_handler(
      servicer.TransferInit,
      request_deserializer=service__pb2.TransferInitRequest.FromString,
      response_serializer=service__pb2.TransferInitResponse.SerializeToString,
    ),
    'AuthTransferInit': grpc.unary_unary_rpc_method_handler(
      servicer.AuthTransferInit,
      request_deserializer=service__pb2.TransferInitRequest.FromString,
      response_serializer=service__pb2.TransferInitResponse.SerializeToString,
    ),
    'TransferInitV2': grpc.unary_unary_rpc_method_handler(
      servicer.TransferInitV2,
      request_deserializer=service__pb2.TransferInitRequest.FromString,
      response_serializer=service__pb2.TransferInitResponse.SerializeToString,
    ),
    'Transfer': grpc.stream_unary_rpc_method_handler(
      servicer.Transfer,
      request_deserializer=service__pb2.TransferRequest.FromString,
      response_serializer=service__pb2.TransferResponse.SerializeToString,
    ),
    'AuthTransfer': grpc.stream_unary_rpc_method_handler(
      servicer.AuthTransfer,
      request_deserializer=service__pb2.TransferRequest.FromString,
      response_serializer=service__pb2.TransferResponse.SerializeToString,
    ),
    'TransferV2': grpc.stream_unary_rpc_method_handler(
      servicer.TransferV2,
      request_deserializer=service__pb2.TransferRequest.FromString,
      response_serializer=service__pb2.TransferResponse.SerializeToString,
    ),
    'TransferFinish': grpc.unary_unary_rpc_method_handler(
      servicer.TransferFinish,
      request_deserializer=service__pb2.TransferFinishRequest.FromString,
      response_serializer=service__pb2.TransferFinishResponse.SerializeToString,
    ),
    'AuthTransferFinish': grpc.unary_unary_rpc_method_handler(
      servicer.AuthTransferFinish,
      request_deserializer=service__pb2.TransferFinishRequest.FromString,
      response_serializer=service__pb2.TransferFinishResponse.SerializeToString,
    ),
    'TransferFinishV2': grpc.unary_unary_rpc_method_handler(
      servicer.TransferFinishV2,
      request_deserializer=service__pb2.TransferFinishRequest.FromString,
      response_serializer=service__pb2.TransferFinishResponse.SerializeToString,
    ),
    'StorageInit': grpc.unary_unary_rpc_method_handler(
      servicer.StorageInit,
      request_deserializer=service__pb2.StorageInitRequest.FromString,
      response_serializer=service__pb2.StorageInitResponse.SerializeToString,
    ),
    'AuthStorageInit': grpc.unary_unary_rpc_method_handler(
      servicer.AuthStorageInit,
      request_deserializer=service__pb2.StorageInitRequest.FromString,
      response_serializer=service__pb2.StorageInitResponse.SerializeToString,
    ),
    'StorageInitV2': grpc.unary_unary_rpc_method_handler(
      servicer.StorageInitV2,
      request_deserializer=service__pb2.StorageInitRequest.FromString,
      response_serializer=service__pb2.StorageInitResponse.SerializeToString,
    ),
    'StorageFinish': grpc.unary_unary_rpc_method_handler(
      servicer.StorageFinish,
      request_deserializer=service__pb2.StorageFinishRequest.FromString,
      response_serializer=service__pb2.StorageFinishResponse.SerializeToString,
    ),
    'AuthStorageFinish': grpc.unary_unary_rpc_method_handler(
      servicer.AuthStorageFinish,
      request_deserializer=service__pb2.StorageFinishRequest.FromString,
      response_serializer=service__pb2.StorageFinishResponse.SerializeToString,
    ),
    'StorageFinishV2': grpc.unary_unary_rpc_method_handler(
      servicer.StorageFinishV2,
      request_deserializer=service__pb2.StorageFinishRequest.FromString,
      response_serializer=service__pb2.StorageFinishResponse.SerializeToString,
    ),
    'UploadInit': grpc.unary_unary_rpc_method_handler(
      servicer.UploadInit,
      request_deserializer=service__pb2.UploadInitRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'AuthUploadInit': grpc.unary_unary_rpc_method_handler(
      servicer.AuthUploadInit,
      request_deserializer=service__pb2.UploadInitRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'UploadInitV2': grpc.unary_unary_rpc_method_handler(
      servicer.UploadInitV2,
      request_deserializer=service__pb2.UploadInitRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'UploadBasic': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasic,
      request_deserializer=service__pb2.UploadRequest.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'UploadBasicV2': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasicV2,
      request_deserializer=service__pb2.UploadRequest.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'UploadBasicV3': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasicV3,
      request_deserializer=service__pb2.UploadV3Request.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'UploadBasicV4': grpc.stream_unary_rpc_method_handler(
      servicer.UploadBasicV4,
      request_deserializer=service__pb2.UploadV3Request.FromString,
      response_serializer=service__pb2.UploadResponse.SerializeToString,
    ),
    'TransferToUpload': grpc.unary_unary_rpc_method_handler(
      servicer.TransferToUpload,
      request_deserializer=service__pb2.TransferToUploadRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'TransferToStorage': grpc.unary_unary_rpc_method_handler(
      servicer.TransferToStorage,
      request_deserializer=service__pb2.TransferToStorageRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'AuthTransferToUpload': grpc.unary_unary_rpc_method_handler(
      servicer.AuthTransferToUpload,
      request_deserializer=service__pb2.TransferToUploadRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'AuthTransferToStorage': grpc.unary_unary_rpc_method_handler(
      servicer.AuthTransferToStorage,
      request_deserializer=service__pb2.TransferToStorageRequest.FromString,
      response_serializer=service__pb2.UploadInitResponse.SerializeToString,
    ),
    'Download': grpc.unary_stream_rpc_method_handler(
      servicer.Download,
      request_deserializer=service__pb2.DownloadRequest.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'DownloadV2': grpc.unary_stream_rpc_method_handler(
      servicer.DownloadV2,
      request_deserializer=service__pb2.DownloadV2Request.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'AuthDownload': grpc.unary_stream_rpc_method_handler(
      servicer.AuthDownload,
      request_deserializer=service__pb2.DownloadRequest.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'AuthDownloadV2': grpc.unary_stream_rpc_method_handler(
      servicer.AuthDownloadV2,
      request_deserializer=service__pb2.DownloadV2Request.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'DownloadV3': grpc.unary_stream_rpc_method_handler(
      servicer.DownloadV3,
      request_deserializer=service__pb2.DownloadRequest.FromString,
      response_serializer=service__pb2.DownloadResponse.SerializeToString,
    ),
    'DownloadV4': grpc.unary_unary_rpc_method_handler(
      servicer.DownloadV4,
      request_deserializer=service__pb2.DownloadV4Request.FromString,
      response_serializer=service__pb2.DownloadV4Response.SerializeToString,
    ),
    'AuthDownloadV4': grpc.unary_unary_rpc_method_handler(
      servicer.AuthDownloadV4,
      request_deserializer=service__pb2.DownloadV4Request.FromString,
      response_serializer=service__pb2.DownloadV4Response.SerializeToString,
    ),
    'DownloadInfo': grpc.unary_unary_rpc_method_handler(
      servicer.DownloadInfo,
      request_deserializer=service__pb2.DownloadInfoRequest.FromString,
      response_serializer=service__pb2.DownloadInfoResponse.SerializeToString,
    ),
    'AuthDownloadInfo': grpc.unary_unary_rpc_method_handler(
      servicer.AuthDownloadInfo,
      request_deserializer=service__pb2.DownloadInfoRequest.FromString,
      response_serializer=service__pb2.DownloadInfoResponse.SerializeToString,
    ),
    'Delete': grpc.unary_unary_rpc_method_handler(
      servicer.Delete,
      request_deserializer=service__pb2.DeleteRequest.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'AuthDelete': grpc.unary_unary_rpc_method_handler(
      servicer.AuthDelete,
      request_deserializer=service__pb2.DeleteRequest.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'DeleteV2': grpc.unary_unary_rpc_method_handler(
      servicer.DeleteV2,
      request_deserializer=service__pb2.DeleteRequest.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'DeleteV3': grpc.unary_unary_rpc_method_handler(
      servicer.DeleteV3,
      request_deserializer=service__pb2.DeleteV3Request.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'AuthDeleteV3': grpc.unary_unary_rpc_method_handler(
      servicer.AuthDeleteV3,
      request_deserializer=service__pb2.DeleteV3Request.FromString,
      response_serializer=service__pb2.DeleteResponse.SerializeToString,
    ),
    'Message': grpc.unary_unary_rpc_method_handler(
      servicer.Message,
      request_deserializer=service__pb2.MessageRequest.FromString,
      response_serializer=service__pb2.MessageResponse.SerializeToString,
    ),
    'AuthMessage': grpc.unary_unary_rpc_method_handler(
      servicer.AuthMessage,
      request_deserializer=service__pb2.MessageRequest.FromString,
      response_serializer=service__pb2.MessageResponse.SerializeToString,
    ),
    'DropAccount': grpc.unary_unary_rpc_method_handler(
      servicer.DropAccount,
      request_deserializer=service__pb2.DropAccountRequest.FromString,
      response_serializer=service__pb2.DropAccountResponse.SerializeToString,
    ),
    'AuthDropAccount': grpc.unary_unary_rpc_method_handler(
      servicer.AuthDropAccount,
      request_deserializer=service__pb2.DropAccountRequest.FromString,
      response_serializer=service__pb2.DropAccountResponse.SerializeToString,
    ),
    'Heartbeat': grpc.unary_unary_rpc_method_handler(
      servicer.Heartbeat,
      request_deserializer=service__pb2.Empty.FromString,
      response_serializer=service__pb2.Empty.SerializeToString,
    ),
    'RequestsUpdate': grpc.unary_unary_rpc_method_handler(
      servicer.RequestsUpdate,
      request_deserializer=service__pb2.RequestsUpdateRequest.FromString,
      response_serializer=service__pb2.RequestsResponse.SerializeToString,
    ),
    'RequestsCreate': grpc.unary_unary_rpc_method_handler(
      servicer.RequestsCreate,
      request_deserializer=service__pb2.RequestsCreateRequest.FromString,
      response_serializer=service__pb2.RequestsResponse.SerializeToString,
    ),
    'AuthRequestsUpdate': grpc.unary_unary_rpc_method_handler(
      servicer.AuthRequestsUpdate,
      request_deserializer=service__pb2.RequestsUpdateRequest.FromString,
      response_serializer=service__pb2.RequestsResponse.SerializeToString,
    ),
    'AuthRequestsCreate': grpc.unary_unary_rpc_method_handler(
      servicer.AuthRequestsCreate,
      request_deserializer=service__pb2.RequestsCreateRequest.FromString,
      response_serializer=service__pb2.RequestsResponse.SerializeToString,
    ),
    'DataRoomCreate': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomCreate,
      request_deserializer=service__pb2.DataRoomCreateRequest.FromString,
      response_serializer=service__pb2.DataRoomCreateResponse.SerializeToString,
    ),
    'DataRoomDelete': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomDelete,
      request_deserializer=service__pb2.DataRoomDeleteRequest.FromString,
      response_serializer=service__pb2.DataRoomDeleteResponse.SerializeToString,
    ),
    'DataRoomPolicyCreate': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomPolicyCreate,
      request_deserializer=service__pb2.DataRoomPolicyCreateRequest.FromString,
      response_serializer=service__pb2.DataRoomPolicyCreateResponse.SerializeToString,
    ),
    'DataRoomPolicyDelete': grpc.unary_unary_rpc_method_handler(
      servicer.DataRoomPolicyDelete,
      request_deserializer=service__pb2.DataRoomPolicyDeleteRequest.FromString,
      response_serializer=service__pb2.DataRoomPolicyDeleteResponse.SerializeToString,
    ),
    'DataPolicyCreate': grpc.unary_unary_rpc_method_handler(
      servicer.DataPolicyCreate,
      request_deserializer=service__pb2.DataPolicyCreateRequest.FromString,
      response_serializer=service__pb2.DataPolicyCreateResponse.SerializeToString,
    ),
    'DataPolicyDelete': grpc.unary_unary_rpc_method_handler(
      servicer.DataPolicyDelete,
      request_deserializer=service__pb2.DataPolicyDeleteRequest.FromString,
      response_serializer=service__pb2.DataPolicyDeleteResponse.SerializeToString,
    ),
    'DataLogs': grpc.unary_unary_rpc_method_handler(
      servicer.DataLogs,
      request_deserializer=service__pb2.DataLogListRequest.FromString,
      response_serializer=service__pb2.DataLogListResponse.SerializeToString,
    ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
    'service.tcRpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class tcRpc(object):
  """Missing associated documentation comment in .proto file."""

  @staticmethod
  def TransferInit(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/TransferInit',
                                         service__pb2.TransferInitRequest.SerializeToString,
                                         service__pb2.TransferInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthTransferInit(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthTransferInit',
                                         service__pb2.TransferInitRequest.SerializeToString,
                                         service__pb2.TransferInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferInitV2(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/TransferInitV2',
                                         service__pb2.TransferInitRequest.SerializeToString,
                                         service__pb2.TransferInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Transfer(request_iterator,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.tcRpc/Transfer',
                                          service__pb2.TransferRequest.SerializeToString,
                                          service__pb2.TransferResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthTransfer(request_iterator,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.tcRpc/AuthTransfer',
                                          service__pb2.TransferRequest.SerializeToString,
                                          service__pb2.TransferResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferV2(request_iterator,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.tcRpc/TransferV2',
                                          service__pb2.TransferRequest.SerializeToString,
                                          service__pb2.TransferResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferFinish(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/TransferFinish',
                                         service__pb2.TransferFinishRequest.SerializeToString,
                                         service__pb2.TransferFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthTransferFinish(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthTransferFinish',
                                         service__pb2.TransferFinishRequest.SerializeToString,
                                         service__pb2.TransferFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferFinishV2(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/TransferFinishV2',
                                         service__pb2.TransferFinishRequest.SerializeToString,
                                         service__pb2.TransferFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageInit(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/StorageInit',
                                         service__pb2.StorageInitRequest.SerializeToString,
                                         service__pb2.StorageInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthStorageInit(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthStorageInit',
                                         service__pb2.StorageInitRequest.SerializeToString,
                                         service__pb2.StorageInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageInitV2(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/StorageInitV2',
                                         service__pb2.StorageInitRequest.SerializeToString,
                                         service__pb2.StorageInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageFinish(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/StorageFinish',
                                         service__pb2.StorageFinishRequest.SerializeToString,
                                         service__pb2.StorageFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthStorageFinish(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthStorageFinish',
                                         service__pb2.StorageFinishRequest.SerializeToString,
                                         service__pb2.StorageFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def StorageFinishV2(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/StorageFinishV2',
                                         service__pb2.StorageFinishRequest.SerializeToString,
                                         service__pb2.StorageFinishResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadInit(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/UploadInit',
                                         service__pb2.UploadInitRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthUploadInit(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthUploadInit',
                                         service__pb2.UploadInitRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadInitV2(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/UploadInitV2',
                                         service__pb2.UploadInitRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasic(request_iterator,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.tcRpc/UploadBasic',
                                          service__pb2.UploadRequest.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasicV2(request_iterator,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.tcRpc/UploadBasicV2',
                                          service__pb2.UploadRequest.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasicV3(request_iterator,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.tcRpc/UploadBasicV3',
                                          service__pb2.UploadV3Request.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def UploadBasicV4(request_iterator,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
    return grpc.experimental.stream_unary(request_iterator, target, '/service.tcRpc/UploadBasicV4',
                                          service__pb2.UploadV3Request.SerializeToString,
                                          service__pb2.UploadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferToUpload(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/TransferToUpload',
                                         service__pb2.TransferToUploadRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def TransferToStorage(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/TransferToStorage',
                                         service__pb2.TransferToStorageRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthTransferToUpload(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthTransferToUpload',
                                         service__pb2.TransferToUploadRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthTransferToStorage(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthTransferToStorage',
                                         service__pb2.TransferToStorageRequest.SerializeToString,
                                         service__pb2.UploadInitResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Download(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.tcRpc/Download',
                                          service__pb2.DownloadRequest.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadV2(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.tcRpc/DownloadV2',
                                          service__pb2.DownloadV2Request.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthDownload(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.tcRpc/AuthDownload',
                                          service__pb2.DownloadRequest.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthDownloadV2(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.tcRpc/AuthDownloadV2',
                                          service__pb2.DownloadV2Request.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadV3(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_stream(request, target, '/service.tcRpc/DownloadV3',
                                          service__pb2.DownloadRequest.SerializeToString,
                                          service__pb2.DownloadResponse.FromString,
                                          options, channel_credentials,
                                          insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadV4(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DownloadV4',
                                         service__pb2.DownloadV4Request.SerializeToString,
                                         service__pb2.DownloadV4Response.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthDownloadV4(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthDownloadV4',
                                         service__pb2.DownloadV4Request.SerializeToString,
                                         service__pb2.DownloadV4Response.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DownloadInfo(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DownloadInfo',
                                         service__pb2.DownloadInfoRequest.SerializeToString,
                                         service__pb2.DownloadInfoResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthDownloadInfo(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthDownloadInfo',
                                         service__pb2.DownloadInfoRequest.SerializeToString,
                                         service__pb2.DownloadInfoResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Delete(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/Delete',
                                         service__pb2.DeleteRequest.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthDelete(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthDelete',
                                         service__pb2.DeleteRequest.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DeleteV2(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DeleteV2',
                                         service__pb2.DeleteRequest.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DeleteV3(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DeleteV3',
                                         service__pb2.DeleteV3Request.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthDeleteV3(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthDeleteV3',
                                         service__pb2.DeleteV3Request.SerializeToString,
                                         service__pb2.DeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Message(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/Message',
                                         service__pb2.MessageRequest.SerializeToString,
                                         service__pb2.MessageResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthMessage(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthMessage',
                                         service__pb2.MessageRequest.SerializeToString,
                                         service__pb2.MessageResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DropAccount(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DropAccount',
                                         service__pb2.DropAccountRequest.SerializeToString,
                                         service__pb2.DropAccountResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthDropAccount(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthDropAccount',
                                         service__pb2.DropAccountRequest.SerializeToString,
                                         service__pb2.DropAccountResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def Heartbeat(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/Heartbeat',
                                         service__pb2.Empty.SerializeToString,
                                         service__pb2.Empty.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def RequestsUpdate(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/RequestsUpdate',
                                         service__pb2.RequestsUpdateRequest.SerializeToString,
                                         service__pb2.RequestsResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def RequestsCreate(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/RequestsCreate',
                                         service__pb2.RequestsCreateRequest.SerializeToString,
                                         service__pb2.RequestsResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthRequestsUpdate(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthRequestsUpdate',
                                         service__pb2.RequestsUpdateRequest.SerializeToString,
                                         service__pb2.RequestsResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def AuthRequestsCreate(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/AuthRequestsCreate',
                                         service__pb2.RequestsCreateRequest.SerializeToString,
                                         service__pb2.RequestsResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomCreate(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DataRoomCreate',
                                         service__pb2.DataRoomCreateRequest.SerializeToString,
                                         service__pb2.DataRoomCreateResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomDelete(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DataRoomDelete',
                                         service__pb2.DataRoomDeleteRequest.SerializeToString,
                                         service__pb2.DataRoomDeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomPolicyCreate(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DataRoomPolicyCreate',
                                         service__pb2.DataRoomPolicyCreateRequest.SerializeToString,
                                         service__pb2.DataRoomPolicyCreateResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataRoomPolicyDelete(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DataRoomPolicyDelete',
                                         service__pb2.DataRoomPolicyDeleteRequest.SerializeToString,
                                         service__pb2.DataRoomPolicyDeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataPolicyCreate(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DataPolicyCreate',
                                         service__pb2.DataPolicyCreateRequest.SerializeToString,
                                         service__pb2.DataPolicyCreateResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataPolicyDelete(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DataPolicyDelete',
                                         service__pb2.DataPolicyDeleteRequest.SerializeToString,
                                         service__pb2.DataPolicyDeleteResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

  @staticmethod
  def DataLogs(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
    return grpc.experimental.unary_unary(request, target, '/service.tcRpc/DataLogs',
                                         service__pb2.DataLogListRequest.SerializeToString,
                                         service__pb2.DataLogListResponse.FromString,
                                         options, channel_credentials,
                                         insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
